

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RackPeople.BillingAPI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BillingEntities : DbContext
{
    public BillingEntities()
        : base("name=BillingEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Subscription> Subscriptions { get; set; }

    public virtual DbSet<TeleAgreement> TeleAgreements { get; set; }

    public virtual DbSet<TeleNumberSeries> TeleNumberSeries { get; set; }

    public virtual DbSet<Audit> Audits { get; set; }

    public virtual DbSet<TeleProduct> TeleProducts { get; set; }

    public virtual DbSet<TeleBillingImport> TeleBillingImport { get; set; }

}

}

