
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RackPeople.BillingAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public int Id { get; set; }

    public int BillingSubscriptionId { get; set; }

    public string NavProductNumber { get; set; }

    public string Description { get; set; }

    public string UnitType { get; set; }

    public decimal UnitAmount { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal NavPrice { get; set; }

}

}
