//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackPeople.BillingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string NavCustomerId { get; set; }
        public string BillingCycle { get; set; }
        public System.DateTime FirstInvoice { get; set; }
        public System.DateTime NextInvoice { get; set; }
        public string NavCustomerName { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public string AdditionalText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
