//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackPeople.BillingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleAgreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeleAgreement()
        {
            this.Numbers = new HashSet<TeleNumberSeries>();
        }
    
        public long Id { get; set; }
        public string NavCustomerId { get; set; }
        public string NavCustomerName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeleNumberSeries> Numbers { get; set; }
    }
}
