//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackPeople.BillingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleProduct
    {
        public long Id { get; set; }
        public long TeleNumberSeriesId { get; set; }
        public string NavProductNumber { get; set; }
        public decimal NavProductPrice { get; set; }
        public string Description { get; set; }
        public string Prefix { get; set; }
        public string UnitType { get; set; }
        public decimal UnitPrice { get; set; }
        public short DestinationType { get; set; }
        public short ProductType { get; set; }
    }
}
