//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RackPeople.BillingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleNumberSeries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeleNumberSeries()
        {
            this.Products = new HashSet<TeleProduct>();
        }
    
        public long Id { get; set; }
        public long TeleAgreementId { get; set; }
        public string Numbers { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeleProduct> Products { get; set; }
    }
}
