//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RPNAVConnect.TimeLogDataWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RPNAVConnectWSSoap", Namespace="https://nav.gowingu.net:8091/")]
    public partial class RPNAVConnectWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTimeLogDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RPNAVConnectWS() {
            this.Url = global::RPNAVConnect.Properties.Settings.Default.RPNAVConnect_TimeLogDataWS_RPNAVConnectWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTimeLogDataCompletedEventHandler GetTimeLogDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://nav.gowingu.net:8091/GetTimeLogData", RequestNamespace="https://nav.gowingu.net:8091/", ResponseNamespace="https://nav.gowingu.net:8091/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public strRPNAVConnectWS GetTimeLogData(string sVATNos, string sInvoiceStatus, string sStartMonth, string sStartYear, string sEndMonth, string sEndYear) {
            object[] results = this.Invoke("GetTimeLogData", new object[] {
                        sVATNos,
                        sInvoiceStatus,
                        sStartMonth,
                        sStartYear,
                        sEndMonth,
                        sEndYear});
            return ((strRPNAVConnectWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeLogDataAsync(string sVATNos, string sInvoiceStatus, string sStartMonth, string sStartYear, string sEndMonth, string sEndYear) {
            this.GetTimeLogDataAsync(sVATNos, sInvoiceStatus, sStartMonth, sStartYear, sEndMonth, sEndYear, null);
        }
        
        /// <remarks/>
        public void GetTimeLogDataAsync(string sVATNos, string sInvoiceStatus, string sStartMonth, string sStartYear, string sEndMonth, string sEndYear, object userState) {
            if ((this.GetTimeLogDataOperationCompleted == null)) {
                this.GetTimeLogDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeLogDataOperationCompleted);
            }
            this.InvokeAsync("GetTimeLogData", new object[] {
                        sVATNos,
                        sInvoiceStatus,
                        sStartMonth,
                        sStartYear,
                        sEndMonth,
                        sEndYear}, this.GetTimeLogDataOperationCompleted, userState);
        }
        
        private void OnGetTimeLogDataOperationCompleted(object arg) {
            if ((this.GetTimeLogDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeLogDataCompleted(this, new GetTimeLogDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nav.gowingu.net:8091/")]
    public partial class strRPNAVConnectWS {
        
        private string sResultDescField;
        
        private string sResultCustomersField;
        
        private string sResultInvoicesField;
        
        private string sResultInvoiceLinesField;
        
        /// <remarks/>
        public string sResultDesc {
            get {
                return this.sResultDescField;
            }
            set {
                this.sResultDescField = value;
            }
        }
        
        /// <remarks/>
        public string sResultCustomers {
            get {
                return this.sResultCustomersField;
            }
            set {
                this.sResultCustomersField = value;
            }
        }
        
        /// <remarks/>
        public string sResultInvoices {
            get {
                return this.sResultInvoicesField;
            }
            set {
                this.sResultInvoicesField = value;
            }
        }
        
        /// <remarks/>
        public string sResultInvoiceLines {
            get {
                return this.sResultInvoiceLinesField;
            }
            set {
                this.sResultInvoiceLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetTimeLogDataCompletedEventHandler(object sender, GetTimeLogDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeLogDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeLogDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public strRPNAVConnectWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((strRPNAVConnectWS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591